name: wf-ci-develop

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize]

jobs:
  linting-develop-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint HTML Files with HTMLHint
        run: npx htmlhint "**/*.html"

      - name: Install Stylelint v15
        run: npm install stylelint@15.11.0

      - name: Lint CSS Files with Stylelint
        run: npx stylelint "**/*.css"